--- 
title: "HKU Single-cell Workshop (Modules 4.2 & 5)"
author: "Yuanhua Lab: Mingze Gao, Rongting Huang, Xianjie Huang, Aaron Kwok, Zhuoxuan Li, Chen Qiao, Yuanhua Huang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Cell trajectory inference; Cellular genetic analysis"
---

# Introduction

This sub-tutorial book is for the Modules 4.2 and 5 of [Single-cell Workshop at HKU](https://statbiomed.github.io/HKU-single-cell-workshop/).

You can fork or download this tutorial book (and re-run it) from this GitHub repo: https://github.com/StatBiomed/SingleCell-Workshop-2021


## Contents of this part

- **Module 4.2: Cell trajectory inference**
  - Overview of trajectory inference
  - RNA velocity
  - Diffusion pseudotime

- **Module 5: Cellular genetic analysis**
  - SNV analysis in single-cell omics
  - mtDNA variants for lineage tracing
  - Copy number variation analysis from scRNA-seq


## Other modules of this workshop
- Module 1: Introduction to R by Dr Joshua Ho & lab ([Online tutorials](https://holab-hku.github.io/Fundamental-scRNA/))

- Module 2: Fundamentals of scRNA-seq analysis by Dr Joshua Ho (([Online tutorials](https://holab-hku.github.io/Fundamental-scRNA/)))

  Materials will come soon...
  
- Module 3: Cell clustering and annotation by Dr Asif Javed ([Online tutorials](https://github.com/pkuerten/single_cell_clustering_annotation.github.io/blob/main/index.md))

  Materials will come soon...

- Module 4.1: Cell interaction by Dr Asif Javed ([Online tutorials](https://github.com/pkuerten/single_cell_clustering_annotation.github.io/blob/main/index.md))


**Note**: to build this book, use the following script in R:
```
bookdown::render_book("index.Rmd", "bookdown::gitbook")
```
